#!/bin/bash
set -e

echo "Enviando 2 requisições de 1 em 1 para um endpoint que faz um processamento de dados em JAVASCRIPT"
ab -c 1 -n 2 -r http://localhost:3000/js_sync

echo
echo
echo "Enviando 2 requisições de 1 em 1 para um endpoint que faz um processamento de dados utilizando um ADDON"
ab -c 1 -n 2 -r http://localhost:3000/cpp_sync

echo
echo
echo "Enviando uma requisição a cada 5 segundo para os mesmos endpoints"
while true
do
    curl -s http://localhost:3000/js_sync > /dev/null &
    curl -s http://localhost:3000/cpp_sync > /dev/null &
    sleep 5
done
