#!/bin/bash
set -e

# Note que apesar de realizar 10 conexões simultâneas com o servidor, apenas 4 são respondidas de cada vez
echo "Enviando 100 requisições de 10 em 10 para um endpoint que faz um processamento de dados em C++ assincronamente"
ab -c 10 -n 100 -r http://localhost:3000/cpp_async
